### ISSUE TITLE
How were these scales discretized in “agreement” and “disagreement”?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/SIGCSE2021#12]
How were these scales (Likert and slider) discretized in “agreement” and “disagreement” for Chi-square tests? Did the authors define scores based on the slider scale and/or Likert scale? Or what data they considered in Chi-square testes? What were the adopted scores? Why these scores were adopted?

**Comment by CathrynKnight** [comment]
"5 point Likert scales were utilized (strongly agree; agree; neither agree nor disagree; disagree; strongly disagree)". (Then when talking about chi-squared) "For the purpose of the chi-squared tests, the Likert scales were coded into a binary 'agree' and 'disagree' variables. This allowed for ease of interpretation and to see which groups were significantly more likely than expected to agree or disagree with each statement".

I would get rid of mention of slider scales because we don't refer to them in the results
